### ISSUE TITLE
Simplify hand format parser

### ISSUE THREAD

**Issue by Iipin** [riichi/chombot#6]
Currently `!hand` command scans hand description from left to right, which complicates things a bit – tile suite is specified *after* a sequence of tiles, so we need to either remember tiles with unspecified suite (which is the current solution) or do a forward lookup first. Parsing from right to left should simplify the whole process.

**Comment by m4tx** [comment]
Currently in scope of https://github.com/m4tx/riichi-hand-rs project, closing the issue.

Also, having it done this way has one big advantage: you can find the first character in the description which causes an error - it would be impossible when parsing the hand right-to-left.
