### ISSUE TITLE
Cache tile images in PNGHandRenderer

### ISSUE THREAD

**Issue by Iipin** [riichi/chombot#8]
Currently `commands.hand.PNGHandRenderer`, when asked to load an image file, reloads it from disk every time, which is probably not a very good thing – there are not that many tiles to begin with and some of them are heavily reused (e.g. `Front.png`). It would be nice if it could read each tile at most once – either eagerly (read all tiles at startup) or lazily (read from disk when necessary and store result for later).

**Comment by m4tx** [comment]
Fixed in the Rust version.
